### ISSUE TITLE
We need the WEB up again in production!!! 🚨

### ISSUE THREAD

**Issue by GDeDev** [LarsEjaas/bruce-willis-app#1]
We are Bruce's lovers. You and your code is one of my source inspiration for continue coding. 
You can check this in my profile´s stars.

We hope you are feel good, and we are waiting for view this fantastic app running again asap. We're at your disposal. 🇦🇷
@LarsEjaas

**Comment by LarsEjaas** [comment]
> We are Bruce's lovers. You and your code is one of my source inspiration for continue coding. You can check this in my profile´s stars.
> 
> We hope you are feel good, and we are waiting for view this fantastic app running again asap. We're at your disposal. 🇦🇷 @LarsEjaas

Hi GDeDev. Thanks for the kind words. 

I am a bit unsure if you experienced any issues with the app? But otherwise, nice to hear that you enjoy using it.
Best regards
Lars
